//! JSON filing artifact for audit-ready risk-layer outputs.

use crate::explainability::ExplainabilityResult;
use crate::premium_calculation::Premium;
use contracts::{FeatureVersion, RiskFeatureBundle, SiteTime};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RateFilingArtifact {
    pub version: FeatureVersion,
    pub generated_at: SiteTime,
    pub feature_bundles: Vec<RiskFeatureBundle>,
    pub premiums: Vec<Premium>,
    pub explainability: ExplainabilityResult,
    pub notes: Vec<String>,
}

impl RateFilingArtifact {
    pub fn new(
        feature_bundles: Vec<RiskFeatureBundle>,
        premiums: Vec<Premium>,
        explainability: ExplainabilityResult,
    ) -> Self {
        Self {
            version: FeatureVersion::default(),
            generated_at: SiteTime::now(),
            feature_bundles,
            premiums,
            explainability,
            notes: vec!["Generated by risk_layer buildable pipeline".to_string()],
        }
    }

    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    pub fn validate(&self) -> Result<(), String> {
        if self
            .premiums
            .iter()
            .any(|premium| premium.final_premium <= 0.0 || !premium.final_premium.is_finite())
        {
            return Err("premiums must be positive finite values".to_string());
        }
        Ok(())
    }
}
