[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[dependencies]
actuarial = { path = "../actuarial" }
control_plane = { path = "../control_plane" }
contracts = { path = "../contracts" }
ndarray = "0.15"
risk_layer = { path = "../risk_layer" }
safety_layer = { path = "../safety_layer" }
shared = { path = "../shared" }
synthetic = { path = "../synthetic" }
serde_json = "1.0"
vla_layer = { path = "../vla_layer" }
