[package]
name = "bil-mock"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Synthetic workflows for BIL SDK"

[dependencies]
bil-core = { path = "../bil-core" }
bil-mir = { path = "../bil-mir" }
bil-canonical = { path = "../bil-canonical" }
bil-replay = { path = "../bil-replay" }
serde.workspace = true
thiserror.workspace = true
