[package]
name = "bil-canonical"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Canonical encoding for BIL SDK"

[dependencies]
bil-core = { path = "../bil-core" }
serde.workspace = true
thiserror.workspace = true
sha2.workspace = true
ciborium = "0.2.2"
hex = "0.4.3"
serde_json.workspace = true
chrono = "0.4.45"
base64 = "0.22.1"
