[package]
name = "bil-verify"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Verification engine for BIL SDK"

[dependencies]
bil-core = { path = "../bil-core" }
bil-ink = { path = "../bil-ink" }
serde.workspace = true
thiserror.workspace = true
