[package]
name = "bil-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for BIL SDK"

[dependencies]
bil-core = { path = "../bil-core" }
bil-mir = { path = "../bil-mir" }
anyhow.workspace = true
clap = { version = "4.6.1", features = ["derive"] }
